### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'name'

### ISSUE THREAD

**Issue by outpaddling** [PacificBiosciences/cDNA_primer#11]
Any hints as to what might cause the error below?  It seems to be a common type of incompatibility issue with Python apps, but I wouldn't know where to start looking.

cDNA_primer:

7dcd560749106abfcfcd8e5097e1f3941ea3141a
I'm using the bundled daligner and dazz_db, although I get the same error with the latest versions + just the bundled LA4Ice

blasr:

I unfortunately removed the .git dir from this one, but it's from 2015-08-17
```
git clone https://github.com/PacificBiosciences/blasr.git
cd blasr
git pull -u origin master && git submodule update --init
```
pbh5tools: 2.3.0p4
```
pbtranscript.py cluster /home/bacon/PacBio-CLI/Sturgeon/output/flnc.fasta cluster_consensusFA.fasta --nfl_fa /home/bacon/PacBio-CLI/Sturgeon/output/nfl.fasta --bas_fofn /home/bacon/PacBio-CLI/Sturgeon/smrtportal_ROI_results_raw/input.fofn --ccs_fofn /home/bacon/PacBio-CLI/Sturgeon/smrtportal_ROI_results_raw/reads_of_insert.fofn
2015-08-18 09:07:08,432 [ERROR] Exiting pbtranscript with return code 1.
Traceback (most recent call last):
  File "/usr/local/cDNA_primer/bin/pbtranscript.py", line 154, in run
    obj.run()
  File "/usr/local/lib/python2.7/site-packages/pbtools/pbtranscript/Cluster.py", line 271, in run
    use_ccs_qv=self.ice_opts.use_finer_qv)
  File "/usr/local/lib/python2.7/site-packages/pbtools/pbtranscript/ice/IceIterative.py", line 203, in __init__
    self.run_gcon_parallel(self.uc.keys())
  File "/usr/local/lib/python2.7/site-packages/pbtools/pbtranscript/ice/IceIterative.py", line 497, in run_gcon_parallel
    self.run_gcon_parallel_helper(cids)
  File "/usr/local/lib/python2.7/site-packages/pbtools/pbtranscript/ice/IceIterative.py", line 567, in run_gcon_parallel_helper
    in_fa_filename = self.write_in_fasta(cid)
  File "/usr/local/lib/python2.7/site-packages/pbtools/pbtranscript/ice/IceIterative.py", line 789, in write_in_fasta
    self.seq_dict[seqid].sequence))
  File "/usr/local/lib/python2.7/site-packages/pbtools/pbtranscript/io/FastaRandomReader.py", line 53, in __getitem__
    return FastaRecord(name=k, sequence=content)
TypeError: __init__() got an unexpected keyword argument 'name'
```

**Comment by Magdoll** [comment]
Hi,

I think this is a pbcore version mismatch issue.
Please see this closed issue:
https://github.com/PacificBiosciences/cDNA_primer/issues/1

I think you may have to downgrade (or upgrade) to pbcore 0.9.1 which you can do via GitHub downloads.

**Comment by outpaddling** [comment]
That actually seems to have worked.  I was using pbcore 1.2.2, and switching to 0.9.1 eliminated the error.
Thanks.

**Comment by Magdoll** [comment]
Good to hear.

This is the only major change in pbcore I am aware of that is breaking ICE between versions. With the next major release (likely end of the year) I expect not to see this one pop up anymore.
