### ISSUE TITLE
subprocess.CalledProcessError

### ISSUE THREAD

**Issue by 52teth** [PacificBiosciences/cDNA_primer#15]
I try to start running the  tofu_wrap.py program using command:
```
tofu_wrap.py --nfl_fa /share/nas3/tengh/SMRT/test_MCF7/Result/Classify/isoseq_nfl.fasta --ccs_fofn /share/nas3/tengh/SMRT/test_MCF7/Result/ReadsOfInsert/reads_of_insert.fofn --bas_fofn /share/nas3/tengh/SMRT/test_MCF7/input.fofn -d /share/nas3/tengh/SMRT/test_MCF7/Result/cluster/cluster --quiver --gmap_db /share/nas3/tengh/database/gmapdb --gmap_name hg19_gmap --blasr_nproc 24 --quiver_nproc 8 --output_seqid_prefix tissue1 /share/nas3/tengh/SMRT/test_MCF7/Result/Classify/isoseq_flnc.fasta /share/nas3/tengh/SMRT/test_MCF7/Result/cluster/final.consensus.fa
```
but an subprocess.CalledProcessError  occurs: 
```
split input /share/nas3/tengh/SMRT/test_MCF7/Result/Classify/isoseq_flnc.fasta into 18 bins
Making fasta_fofn now
fasta_fofn /share/nas3/tengh/SMRT/test_MCF7/Result/cluster/cluster/fasta_fofn_files/input.fasta.fofn
nfl_dir /share/nas3/tengh/SMRT/test_MCF7/Result/cluster/cluster/fasta_fofn_files
running ICE/Quiver on /share/nas3/tengh/SMRT/test_MCF7/Result/cluster/cluster/0to1kb_part0
daligner: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by daligner)
Traceback (most recent call last):
  File "/share/nas1/tengh/software/SMRT/python_virtualenv/bin/tofu_wrap.py", line 5, in <module>
    pkg_resources.run_script('pbtools.pbtranscript==2.2.3', 'tofu_wrap.py')
  File "/share/nas1/tengh/software/SMRT/python_virtualenv/lib/python2.7/site-packages/pkg_resources.py", line 534, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/share/nas1/tengh/software/SMRT/python_virtualenv/lib/python2.7/site-packages/pkg_resources.py", line 1434, in run_script
    execfile(script_filename, namespace, namespace)
  File "/share/nas1/tengh/software/SMRT/python_virtualenv/lib/python2.7/site-packages/pbtools.pbtranscript-2.2.3-py2.7-linux-x86_64.egg/EGG-INFO/scripts/tofu_wrap.py", line 369, in <module>
    tofu_wrap_main()
  File "/share/nas1/tengh/software/SMRT/python_virtualenv/lib/python2.7/site-packages/pbtools.pbtranscript-2.2.3-py2.7-linux-x86_64.egg/EGG-INFO/scripts/tofu_wrap.py", line 347, in tofu_wrap_main
    obj.run()
  File "/share/nas1/tengh/software/SMRT/python_virtualenv/lib/python2.7/site-packages/pbtools.pbtranscript-2.2.3-py2.7-linux-x86_64.egg/pbtools/pbtranscript/Cluster.py", line 271, in run
    use_ccs_qv=self.ice_opts.use_finer_qv)
  File "/share/nas1/tengh/software/SMRT/python_virtualenv/lib/python2.7/site-packages/pbtools.pbtranscript-2.2.3-py2.7-linux-x86_64.egg/pbtools/pbtranscript/ice/IceIterative.py", line 107, in __init__
    sanity_check_daligner(self.script_dir)
  File "/share/nas1/tengh/software/SMRT/python_virtualenv/lib/python2.7/site-packages/pbtools.pbtranscript-2.2.3-py2.7-linux-x86_64.egg/pbtools/pbtranscript/ice/IceUtils.py", line 57, in sanity_check_daligner
    runner.runHPC(min_match_len=300, output_dir=testDir, sensitive_mode=False)
  File "/share/nas1/tengh/software/SMRT/python_virtualenv/lib/python2.7/site-packages/pbtools.pbtranscript-2.2.3-py2.7-linux-x86_64.egg/pbtools/pbtranscript/icedalign/IceDalignUtils.py", line 222, in runHPC
    local_job_runner(cmds_daligner, num_processes=max(1, min(self.cpus/4, 4))) # max 4 at a time to avoid running out of mem..
  File "/share/nas1/tengh/software/SMRT/python_virtualenv/lib/python2.7/site-packages/pbtools.pbtranscript-2.2.3-py2.7-linux-x86_64.egg/pbtools/pbtranscript/icedalign/IceDalignUtils.py", line 243, in local_job_runner
    rets = pool.map(run_cmd_in_shell, cmds_list)
  File "/share/nas2/genome/biosoft/smrtanalysis/smrtanalysis/current/redist/python2.7/lib/python2.7/multiprocessing/pool.py", line 227, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/share/nas2/genome/biosoft/smrtanalysis/smrtanalysis/current/redist/python2.7/lib/python2.7/multiprocessing/pool.py", line 528, in get
    raise self._value
subprocess.CalledProcessError: Command 'timeout 600 daligner -h35 -k16 -e.80 -l300 -s100 -t10 /share/nas3/tengh/SMRT/test_MCF7/Result/cluster/cluster/0to1kb_part0/scripts/daligner_test_dir/gcon_in.dazz.fasta.1 /share/nas3/tengh/SMRT/test_MCF7/Result/cluster/cluster/0to1kb_part0/scripts/daligner_test_dir/gcon_in.dazz.fasta.1' returned non-zero exit status 1
```
I run my cmd on our SGE, is the error related with my SGE?
What should I do with it?
Thanks a lot!

**Comment by bowhan** [comment]
```bash
daligner: /lib64/libc.so.6: version 'GLIBC_2.14' not found (required by daligner)
```
Seems that the node running `daligner` has incompatible shared libraries from the node compiling it (probably not all of your nodes have the same versions of OS). The easiest solution in my opinion would be to re-compile `daligner` and use static linking. 
You can do so by
```bash
cd pbtranscript-tofu/external_daligner/DALIGNER-d4aa4871122b35ac92e2cc13d9b1b1e9c5b5dc5c-ICEmod
# edit the 1st line of Makefile from
CFLAGS = -O3 -Wall -Wextra -fno-strict-aliasing
# to
CFLAGS = -O3 -Wall -Wextra -fno-strict-aliasing -static
# then
make clean
make all
cp HPCdaligner HPCmapper LA4Ice LAcat LAcheck LAmerge \
LAshow LAsort LAsplit daligner $VENV_TOFU/bin
```
You should probably do the same to DAZZ.

**Comment by pb-cdunn** [comment]
I wish we could use static executables everywhere, but Steve Jobs has declared them verboten.

Another options would be to build on the same architecture/OS where you will run.

**Comment by 52teth** [comment]
@bowhan @pb-cdunn 
Thanks a lot!
 It  works well now!

**Comment by 52teth** [comment]
Now I can run the daligner, but another problem troubles me again. When I run the tofu_wrap.py, the following error occurs:
[DEBUG] [IceIterative] 2015-10-28 10:20:13: [IceIterative] Initializing IceIterative.
[DEBUG] [IceIterative] 2015-10-28 10:20:17: [IceIterative] Autodetection of min fasta length: set to under1k (maxScore: -1000, minLength: 300)
[INFO] [IceIterative] 2015-10-28 10:20:17: [IceIterative] Loading probabilities and QVs from given probQV.
[INFO] [IceIterative] 2015-10-28 10:20:17: [IceIterative] Loading initial clusters from uc.
[INFO] [IceIterative] 2015-10-28 10:20:17: [IceIterative] Creating a reference dict using run_gcon_parallel.
[DEBUG] [IceIterative] 2015-10-28 10:20:44: [IceIterative] use_sge = False
[INFO] [IceIterative] 2015-10-28 10:20:44: [IceIterative] Adding 773 threads for ice_pbdagcon jobs
[DEBUG] [IceIterative] 2015-10-28 10:20:44: [IceIterative] Adding a ice_pbdagcon job thread: ice_pbdagcon.py /share/nas3/tengh/SMRT/test_MCF7/classify_seperate/test/Result/Cluster/cluster/0to1kb_part0/tmp/0/c0/in.fa  /share/nas3/tengh/SMRT/test_MCF7/classify_seperate/test/Result/Cluster/cluster/0to1kb_part0/tmp/0/c0/g_consensus c0 --nproc 4 --maxScore -1000
.....
[INFO] [IceIterative] 2015-10-28 11:18:40: [IceIterative] Total time for 335 pbdagcon jobs is 0:05:25.196534.
[INFO] [IceIterative] 2015-10-28 11:20:56: [IceIterative] Total time for choosing 8781 ref files is 0:02:15.369625.
[DEBUG] [IceIterative] 2015-10-28 11:20:56: [IceIterative] Total time for run_gcon_parallel is 0:09:19.005723.
...
[DEBUG] [IceIterative] 2015-10-28 11:21:02: [IceIterative] REMOVING 32440 from changes because no gcon change
[DEBUG] [IceIterative] 2015-10-28 11:32:46: [IceIterative] ERROR! Daligner failed. Switching to blasr. Report bug.
[INFO] [IceIterative] 2015-10-28 11:32:46: [IceIterative] Creating a suffix array for ref_consensus.fa

How can I fix the problem?
Thanks for any advice.

**Comment by Magdoll** [comment]
Hi,

Is the process still running? If it is, I don't see an issue. Well...as in, this was expected. DALIGNER is known to have bugs and in ICE I put in a safety net where if DALIGNER fails it falls back to BLASR. So the fact that you see this message means it is switching back to BLASR for some instances.

If your program continues to run, then it should be fine.

--Liz

**Comment by 52teth** [comment]
Indeed, it still can run. After a while,the "subprocess.CalledProcessError"  appeared and the program died. Here is the error information:
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
putting 507 in ./0to1kb_part0/isoseq_flnc.fasta
...
2015-10-28 22:00:13,935 INFO [main] Multi-threaded. Input: /share/nas3/tengh/SMRT/test_MCF7/classify_seperate/test/Result/cluster/1to2kb_part0/tmp/0/c471/g_consensus.saln, Threads: 4
running ICE/Quiver on /share/nas3/tengh/SMRT/test_MCF7/classify_seperate/test/Result/cluster/2to3kb_part0
running ICE/Quiver on /share/nas3/tengh/SMRT/test_MCF7/classify_seperate/test/Result/cluster/3to4kb_part0
running ICE/Quiver on /share/nas3/tengh/SMRT/test_MCF7/classify_seperate/test/Result/cluster/4to5kb_part0
*** glibc detected *** daligner: free(): invalid next size (fast): 0x00000000021b6ae0 ***
======= Backtrace: =========
[0x443172]
[0x445bdf]
[0x405685]
[0x40191c]
[0x4324eb]
[0x400429]
======= Memory map: ========
00400000-004e8000 r-xp 00000000 00:1c 471076577                          /share/nas1/tengh/software/SMRT/python_virtualenv/bin/daligner
006e7000-006e9000 rw-p 000e7000 00:1c 471076577                          /share/nas1/tengh/software/SMRT/python_virtualenv/bin/daligner
006e9000-006f3000 rw-p 00000000 00:00 0 
021b4000-0221e000 rw-p 00000000 00:00 0                                  [heap]
7fb18ba57000-7fb18ba58000 ---p 00000000 00:00 0 
7fb18ba58000-7fb18c458000 rw-p 00000000 00:00 0 
7fb18ce59000-7fb18ce5a000 ---p 00000000 00:00 0 
7fb18ce5a000-7fb18d85a000 rw-p 00000000 00:00 0 
7fb18d85a000-7fb18d85b000 ---p 00000000 00:00 0 
7fb18d85b000-7fb18e25b000 rw-p 00000000 00:00 0 
7fb18ec5b000-7fb18ec7e000 rw-p 00000000 00:00 0 
7fb18eca0000-7fb18ecc1000 rw-p 00000000 00:00 0 
7fff6e73f000-7fff6e7b3000 rw-p 00000000 00:00 0                          [stack]
7fff6e7ca000-7fff6e7cb000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
*** glibc detected *** daligner: free(): invalid next size (fast): 0x00000000006f8af0 ***
======= Backtrace: =========
[0x443172]
[0x445bdf]
[0x405685]
[0x40191c]
[0x4324eb]
[0x400429]
======= Memory map: ========
00400000-004e8000 r-xp 00000000 00:1c 471076577                          /share/nas1/tengh/software/SMRT/python_virtualenv/bin/daligner
006e7000-006e9000 rw-p 000e7000 00:1c 471076577                          /share/nas1/tengh/software/SMRT/python_virtualenv/bin/daligner
006e9000-006f3000 rw-p 00000000 00:00 0 
006f6000-00760000 rw-p 00000000 00:00 0                                  [heap]
7f014aeb0000-7f014aeb1000 ---p 00000000 00:00 0 
7f014aeb1000-7f014b8b1000 rw-p 00000000 00:00 0 
7f014c2b2000-7f014c2b3000 ---p 00000000 00:00 0 
7f014c2b3000-7f014ccb3000 rw-p 00000000 00:00 0 
7f014ccb3000-7f014ccb4000 ---p 00000000 00:00 0 
7f014ccb4000-7f014d6b4000 rw-p 00000000 00:00 0 
7f014e0b4000-7f014e0d7000 rw-p 00000000 00:00 0 
7f014e0f9000-7f014e11a000 rw-p 00000000 00:00 0 
7fff0f73f000-7fff0f7b2000 rw-p 00000000 00:00 0                          [stack]
7fff0f7b3000-7fff0f7b4000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
**Traceback (most recent call last):
  File "/share/nas1/tengh/software/SMRT/python_virtualenv/bin/tofu_wrap.py", line 5, in <module>
    pkg_resources.run_script('pbtools.pbtranscript==2.2.3', 'tofu_wrap.py')
  File "/share/nas1/tengh/software/SMRT/python_virtualenv/lib/python2.7/site-packages/pkg_resources.py", line 534, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/share/nas1/tengh/software/SMRT/python_virtualenv/lib/python2.7/site-packages/pkg_resources.py", line 1434, in run_script
    execfile(script_filename, namespace, namespace)
  File "/share/nas1/tengh/software/SMRT/python_virtualenv/lib/python2.7/site-packages/pbtools.pbtranscript-2.2.3-py2.7-linux-x86_64.egg/EGG-INFO/scripts/tofu_wrap.py", line 369, in <module>
    tofu_wrap_main()
  File "/share/nas1/tengh/software/SMRT/python_virtualenv/lib/python2.7/site-packages/pbtools.pbtranscript-2.2.3-py2.7-linux-x86_64.egg/EGG-INFO/scripts/tofu_wrap.py", line 347, in tofu_wrap_main
    obj.run()
  File "/share/nas1/tengh/software/SMRT/python_virtualenv/lib/python2.7/site-packages/pbtools.pbtranscript-2.2.3-py2.7-linux-x86_64.egg/pbtools/pbtranscript/Cluster.py", line 273, in run
    self.icec.run()
  File "/share/nas1/tengh/software/SMRT/python_virtualenv/lib/python2.7/site-packages/pbtools.pbtranscript-2.2.3-py2.7-linux-x86_64.egg/pbtools/pbtranscript/ice/IceIterative.py", line 1550, in run
    use_blasr=False)
  File "/share/nas1/tengh/software/SMRT/python_virtualenv/lib/python2.7/site-packages/pbtools.pbtranscript-2.2.3-py2.7-linux-x86_64.egg/pbtools/pbtranscript/ice/IceIterative.py", line 1379, in run_post_ICE_merging
    for r in iters:
  File "/share/nas1/tengh/software/SMRT/python_virtualenv/lib/python2.7/site-packages/pbtools.pbtranscript-2.2.3-py2.7-linux-x86_64.egg/pbtools/pbtranscript/ice/IceIterative.py", line 1407, in find_mergeable_consensus
    las_filenames, las_out_filenames = runner.runHPC(min_match_len=self.minLength, output_dir=output_dir, sensitive_mode=self.daligner_sensitive_mode)
  File "/share/nas1/tengh/software/SMRT/python_virtualenv/lib/python2.7/site-packages/pbtools.pbtranscript-2.2.3-py2.7-linux-x86_64.egg/pbtools/pbtranscript/icedalign/IceDalignUtils.py", line 222, in runHPC
    local_job_runner(cmds_daligner, num_processes=max(1, min(self.cpus/4, 4))) # max 4 at a time to avoid running out of mem..
  File "/share/nas1/tengh/software/SMRT/python_virtualenv/lib/python2.7/site-packages/pbtools.pbtranscript-2.2.3-py2.7-linux-x86_64.egg/pbtools/pbtranscript/icedalign/IceDalignUtils.py", line 243, in local_job_runner
    rets = pool.map(run_cmd_in_shell, cmds_list)
  File "/share/nas2/genome/biosoft/smrtanalysis/smrtanalysis/current/redist/python2.7/lib/python2.7/multiprocessing/pool.py", line 227, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/share/nas2/genome/biosoft/smrtanalysis/smrtanalysis/current/redist/python2.7/lib/python2.7/multiprocessing/pool.py", line 528, in get
    raise self._value
*subprocess.CalledProcessError: Command 'timeout 600 daligner -h35 -k16 -e.80 -l2500 -s100 -t10 /share/nas3/tengh/SMRT/test_MCF7/classify_seperate/test/Result/cluster/4to5kb_part0/output/tmp.consensus.dazz.fasta.1 /share/nas3/tengh/SMRT/test_MCF7/classify_seperate/test/Result/cluster/4to5kb_part0/output/tmp.consensus.dazz.fasta.1' returned non-zero exit status 134.* **
I have  re-compiled  daligner  using static linking as bowhan said. Is there something with my installation of daligner? What should I do?
Thanks for any reply!

**Comment by Magdoll** [comment]
Hi,

I'm guessing that basically DALIGNER ran out of memory here. This time it failed in a place where I did not write a safety net in. 

I have actually never seen DALIGNER run out of memory here (which is why I guess I didn't write a safety net), so even though I can help you avoid using DALIGNER in this part of the code now, I think it may be worth investigating why DALIGNER seems very unstable on your system (@bowhan @pb-cdunn thoughts?)

The hack I suggest here is to simply use BLASR instead of DALIGNER in where this error occurred: 

in pbtools/pbtranscript/ice/IceIterative.py, search for all instances of calls to 
       " self.run_post_ICE_merging "

and set use_BLASR=True. 

ex:

        self.run_post_ICE_merging(consensusFa=self.tmpConsensusFa,
                                  pickleFN=self.tmpPickleFN,
                                  max_iter=3,
                                  use_blasr=False)

change it to

        self.run_post_ICE_merging(consensusFa=self.tmpConsensusFa,
                                  pickleFN=self.tmpPickleFN,
                                  max_iter=3,
                                  use_blasr=True)

this should be at (or near) line: 1336 and 1550. So you just have to change these two points...


--LIz

**Comment by bowhan** [comment]
Is this error reproducible? Can you `ssh` into the specific node running this job and manually execute it:
```bash
daligner -h35 -k16 -e.80 -l2500 -s100 -t10 \
/share/nas3/tengh/SMRT/test_MCF7/classify_seperate/test/Result/cluster/4to5kb_part0/output/tmp.consensus.dazz.fasta.1  \
/share/nas3/tengh/SMRT/test_MCF7/classify_seperate/test/Result/cluster/4to5kb_part0/output/tmp.consensus.dazz.fasta.1
```
using both the `daligner` linked statically (your current one) as well as non-statically (without `-static` in the makefile; but run `make` **on this specific node running it**, as pb-cdunn suggested)? 

If the error is reproducible, can you please send me (bhan `at` pacb.com) this
`/share/nas3/tengh/SMRT/test_MCF7/classify_seperate/test/Result/cluster/4to5kb_part0/output/tmp.consensus.dazz.fasta.1` file?

However, if the error only occurs for `daligner` compiled on the running node but not for the statically linked one, can you please run `uname -a` on both your head node as well as the node running the job and let us know the output? (it is possible that the kernel versions are so different that there are incompatibilities at the system call level, which screws up statically linked binaries). 


Thank you.

**Comment by pb-cdunn** [comment]
> /share/nas3/tengh/SMRT/test_MCF7/classify_seperate/test/Result/cluster/4to5kb_part0/output/tmp.consensus.dazz.fasta.1

And please tell us the size of that file. If it's smallish, I'd like it too. Maybe share via dropbox?
