### ISSUE TITLE
RuntimeError for  blasr program in  'pbtranscript.py cluster' analysis

### ISSUE THREAD

**Issue by 52teth** [PacificBiosciences/cDNA_primer#20]
When I  do the cluster analysis using the following cmd:
```
. /software//smrtanalysis/current/etc/setup.sh && pbtranscript.py cluster /lustre/tengh/project/SMRT/2-3K/result/Classify/isoseq_flnc.fasta /lustre/tengh/project/SMRT/2-3K/result/Cluster/final.consensus.fa --nfl_fa /lustre/tengh/project/SMRT/2-3K/result/Classify/isoseq_nfl.fasta -d /lustre/tengh/project/SMRT/2-3K/result/Cluster/cluster --ccs_fofn /lustre/tengh/project/SMRT/2-3K/result/ReadsOfInsert/reads_of_insert.fofn --bas_fofn /lustre/tengh/project/SMRT/2-3K/input.fofn --cDNA_size between2k3k --quiver --blasr_nproc 5 --quiver_nproc 5
```
 the following erro info is given:
```
RuntimeError: blasr /lustre/tengh/project/SMRT/2-3K/result/Cluster/cluster/current.fasta.orphan.fa /lustre/tengh/project/SMRT/2-3K/result/Cluster/cluster/current.fasta.orphan.fa -m 5 -maxLCPLength 15 -nproc 5 -maxScore -3000 -bestn 24 -nCandidates 24 -out /lustre/tengh/project/SMRT/2-3K/result/Cluster/cluster/current.fasta.orphan.fa.self.blasr
```
Also a file named `core.129218` is produced, which is not seen in other completed run. 
No such error has occurred before I updated my SMRT with  the latest patch 5. So I wonder is there any problem with my update?
So what's the possible reason caused this error? What should I do with it?
Thanks for any advice O(_)O~

Here is the detail error information:
```python
2015-12-12 22:51:58,833 INFO [main] Multi-threaded. Input: /lustre/tengh/project/SMRT/2-3K/result/Cluster/cluster/tmp/2/c22136/g_consensus.saln, Threads: 8
2015-12-12 23:37:28,525 [ERROR] blasr /lustre/tengh/project/SMRT/2-3K/result/Cluster/cluster/current.fasta.orphan.fa /lustre/tengh/project/SMRT/2-3K/result/Cluster/cluster/current.fasta.orphan.fa -m 5 -maxLCPLength 15 -nproc 5 -maxScore -3000 -bestn 24 -nCandidates 24 -out /lustre/tengh/project/SMRT/2-3K/result/Cluster/cluster/current.fasta.orphan.fa.self.blasr exited with -6:
2015-12-12 23:37:28,538 [ERROR] Exiting pbtranscript with return code 1.
Traceback (most recent call last):
  File "/share/nas2/genome/biosoft/smrtanalysis/smrtanalysis/current/analysis/bin/pbtranscript.py", line 146, in run
    obj.run()
  File "/share/nas2/genome/biosoft/smrtanalysis/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/pbtools/pbtranscript/Cluster.py", line 248, in run
    self.icec.run()
  File "/share/nas2/genome/biosoft/smrtanalysis/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/pbtools/pbtranscript/ice/IceIterative.py", line 1361, in run
    self.keep_adding_files(sizes=sizes)
  File "/share/nas2/genome/biosoft/smrtanalysis/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/pbtools/pbtranscript/ice/IceIterative.py", line 1226, in keep_adding_files
    self.add_new_batch(f)
  File "/share/nas2/genome/biosoft/smrtanalysis/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/pbtools/pbtranscript/ice/IceIterative.py", line 1123, in add_new_batch
    sge_opts=self.sge_opts)
  File "/share/nas2/genome/biosoft/smrtanalysis/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/pbtools/pbtranscript/ice/IceInit.py", line 32, in __init__
    ice_opts=ice_opts, sge_opts=sge_opts)
  File "/share/nas2/genome/biosoft/smrtanalysis/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/pbtools/pbtranscript/ice/IceInit.py", line 147, in init_cluster_by_clique
    ice_opts=ice_opts, sge_opts=sge_opts)
  File "/share/nas2/genome/biosoft/smrtanalysis/smrtanalysis/current/redist/python2.7/lib/python2.7/site-packages/pbtools/pbtranscript/ice/IceInit.py", line 53, in _align
    raise RuntimeError (errMsg)
RuntimeError: blasr /lustre/tengh/project/SMRT/2-3K/result/Cluster/cluster/current.fasta.orphan.fa /lustre/tengh/project/SMRT/2-3K/result/Cluster/cluster/current.fasta.orphan.fa -m 5 -maxLCPLength 15 -nproc 5 -maxScore -3000 -bestn 24 -nCandidates 24 -out /lustre/tengh/project/SMRT/2-3K/result/Cluster/cluster/current.fasta.orphan.fa.self.blasr exited with -6:
```

**Comment by Magdoll** [comment]
Looks like BLASR crashed (hence the core.xxx file). 
I'm not sure if it's related to the patrch but can you try running the BLASR command from the cmd line to see if it works:

'''
blasr /lustre/tengh/project/SMRT/2-3K/result/Cluster/cluster/current.fasta.orphan.fa /lustre/tengh/project/SMRT/2-3K/result/Cluster/cluster/current.fasta.orphan.fa -m 5 -maxLCPLength 15 -nproc 5 -maxScore -3000 -bestn 24 -nCandidates 24 -out /lustre/tengh/project/SMRT/2-3K/result/Cluster/cluster/current.fasta.orphan.fa.self.blasr
;;;

**Comment by 52teth** [comment]
Yes. cmd '''blasr /lustre/tengh/project/SMRT/2-3K/result/Cluster/cluster/current.fasta.orphan.fa /lustre/tengh/project/SMRT/2-3K/result/Cluster/cluster/current.fasta.orphan.fa -m 5 -maxLCPLength 15 -nproc 5 -maxScore -3000 -bestn 24 -nCandidates 24 -out /lustre/tengh/project/SMRT/2-3K/result/Cluster/cluster/current.fasta.orphan.fa.self.blasr" can run successfully.

**Comment by Magdoll** [comment]
Is it possible that the node was particularly occupied with other processes at the time? That could be my only guess....sorry if I dont' have anything more insightful...

I suppose one suggestion is to rerun the job and make sure the node is only occupied by the ToFU task.
