### ISSUE TITLE
 'running_jids' referenced before assignment

### ISSUE THREAD

**Issue by ksahlin** [PacificBiosciences/cDNA_primer#22]
Please find error below, I've attached the last part of the logfile.   (All paths specified to pbtranscript.py cluster are full paths, I just repalaced them with < fullpath > here just in case it's delicate information)
```
.
.
.
DEBUG: put in queue: pls2fasta /nfs/brubeck.bx.psu.edu/scratch5/ksahlin/kmak/121015/pa16_3-6kb/m151209_163732_42146_c100926392550000001823199905121695_s1_p0.2.bax.h5  /nfs/thumper.galaxyproject.org/home/ksahlin/prefix/source/pactrans-denovo/scripts/.snakemake/shadow/tmp3aapcdw1/cluster/output/map_noFL/m151209_163732_42146_c100926392550000001823199905121695_s1_p0.2.bax.h5.fasta.tmp -minSubreadLength 300 -minReadScore 750 -trimByRegion /nfs/thumper.galaxyproject.org/home/ksahlin/prefix/source/pactrans-denovo/scripts/.snakemake/shadow/tmp3aapcdw1/cluster/output/map_noFL/m151209_163732_42146_c100926392550000001823199905121695_s1_p0.2.bax.h5.fasta.tmp /nfs/thumper.galaxyproject.org/home/ksahlin/prefix/source/pactrans-denovo/scripts/.snakemake/shadow/tmp3aapcdw1/cluster/output/map_noFL/m151209_163732_42146_c100926392550000001823199905121695_s1_p0.2.bax.h5.fasta
DEBUG: putting in queue: pls2fasta /nfs/brubeck.bx.psu.edu/scratch5/ksahlin/kmak/121015/pa16_3-6kb/m151209_163732_42146_c100926392550000001823199905121695_s1_p0.3.bax.h5  /nfs/thumper.galaxyproject.org/home/ksahlin/prefix/source/pactrans-denovo/scripts/.snakemake/shadow/tmp3aapcdw1/cluster/output/map_noFL/m151209_163732_42146_c100926392550000001823199905121695_s1_p0.3.bax.h5.fasta.tmp -minSubreadLength 300 -minReadScore 750 -trimByRegion /nfs/thumper.galaxyproject.org/home/ksahlin/prefix/source/pactrans-denovo/scripts/.snakemake/shadow/tmp3aapcdw1/cluster/output/map_noFL/m151209_163732_42146_c100926392550000001823199905121695_s1_p0.3.bax.h5.fasta.tmp /nfs/thumper.galaxyproject.org/home/ksahlin/prefix/source/pactrans-denovo/scripts/.snakemake/shadow/tmp3aapcdw1/cluster/output/map_noFL/m151209_163732_42146_c100926392550000001823199905121695_s1_p0.3.bax.h5.fasta
DEBUG: put in queue: pls2fasta /nfs/brubeck.bx.psu.edu/scratch5/ksahlin/kmak/121015/pa16_3-6kb/m151209_163732_42146_c100926392550000001823199905121695_s1_p0.3.bax.h5  /nfs/thumper.galaxyproject.org/home/ksahlin/prefix/source/pactrans-denovo/scripts/.snakemake/shadow/tmp3aapcdw1/cluster/output/map_noFL/m151209_163732_42146_c100926392550000001823199905121695_s1_p0.3.bax.h5.fasta.tmp -minSubreadLength 300 -minReadScore 750 -trimByRegion /nfs/thumper.galaxyproject.org/home/ksahlin/prefix/source/pactrans-denovo/scripts/.snakemake/shadow/tmp3aapcdw1/cluster/output/map_noFL/m151209_163732_42146_c100926392550000001823199905121695_s1_p0.3.bax.h5.fasta.tmp /nfs/thumper.galaxyproject.org/home/ksahlin/prefix/source/pactrans-denovo/scripts/.snakemake/shadow/tmp3aapcdw1/cluster/output/map_noFL/m151209_163732_42146_c100926392550000001823199905121695_s1_p0.3.bax.h5.fasta
2015-12-19 06:51:12,424 [ERROR] Exiting pbtranscript with return code 1.
Traceback (most recent call last):
  File "/nfs/thumper.galaxyproject.org/home/ksahlin/local_python_modules/lib/python2.7/site-packages/pbtools.pbtranscript-2.2.3-py2.7-linux-x86_64.egg/EGG-INFO/scripts/pbtranscript.py", line 154, in run
    obj.run()
  File "/galaxy/home/ksahlin/local_python_modules/lib/python2.7/site-packages/pbtools.pbtranscript-2.2.3-py2.7-linux-x86_64.egg/pbtools/pbtranscript/Cluster.py", line 308, in run
    self.pol.run()
  File "/galaxy/home/ksahlin/local_python_modules/lib/python2.7/site-packages/pbtools.pbtranscript-2.2.3-py2.7-linux-x86_64.egg/pbtools/pbtranscript/Polish.py", line 194, in run
    self.icepq.run()
  File "/galaxy/home/ksahlin/local_python_modules/lib/python2.7/site-packages/pbtools.pbtranscript-2.2.3-py2.7-linux-x86_64.egg/pbtools/pbtranscript/ice/IceQuiverPostprocess.py", line 414, in run
    job_stats = self.check_quiver_jobs_completion()
  File "/galaxy/home/ksahlin/local_python_modules/lib/python2.7/site-packages/pbtools.pbtranscript-2.2.3-py2.7-linux-x86_64.egg/pbtools/pbtranscript/ice/IceQuiverPostprocess.py", line 255, in check_quiver_jobs_completion
    if job_id in running_jids:  # still running, pass
UnboundLocalError: local variable 'running_jids' referenced before assignment
Command exited with non-zero status 1
        Command being timed: "pbtranscript.py cluster <fullpath>/nontargeted/pbtranscript_classify/flnc.fa  <fullpath>/nontargeted/pbtranscript_cluster/final.consensus.fa --nfl_fa  <fullpath>/nontargeted/pbtranscript_classify/nfl.fa -d cluster --ccs_fofn <fullpath>/nontargeted/reads_of_insert.fofn --bas_fofn <fullpath>/input.fofn --quiver --blasr_nproc 63 --quiver_nproc 63"
```

**Comment by ksahlin** [comment]
To add some more information, I'm running the latest master version on github (actually my fork of it, which contains three small fixes, see the pull request, but I doubt that these fixes would lead to the error that I encounter here). I will also run the same command with the official released (command line) version to see if it works. I'll post an update later.

Thank you,
Kristoffer

**Comment by ksahlin** [comment]
The official version does not give the error above and runs to completion. I'm assuming it does not use the pls2fasta binary as i don't see it in the log file.

**Comment by Magdoll** [comment]
This is a bug. 

running_jids is not initialized unless you have --use_sge == True. So if you ran without using SGE (or forgot to use the --use_sge option), then it does not get initialized.

A quick fix is to change the following line:

line 255 in IceQuiverPostProcess.py:

from 
if job_id in running_jids:  # still running, pass

to 

if self.use_sge is True and job_id in running_jids:  # still running, pass

In this way, all jobs that were not finished (but were supposed to be run locally) will automatically be tagged as incomplete.

By the way, I found a few other minor bugs (mostly related to not putting the right information for saving failed jobs, so it would only pop up if the jobs failed) but they won't get put in until the 3.0 version comes out. Sorry if no bugs are going to be fixed until the new version. The 3.0 (BAM-ified) version will be the next release.

--Liz

**Comment by Magdoll** [comment]
By the way, the way this bug showed up also means that you ran ToFU somehow locally but the jobs did not finish -- and this is very unlikely because if the local jobs died, your program should've exited right then and there. The only way this would happen is if you ran ToFU first with --use_sge, then the job died somehow, and you re-ran it with maybe just "ice_quiver.py postprocess --use_sge <dir_name>".

If you ran "ice_quiver.py postprocess" but forgot the "--use_sge" option, then this is likely the reason for the error. It's confusing what "--use_sge" meant here, but it actually mean that you *used* SGE when submitting the quiver jobs, not that you are about to use SGE for post processing Quiver jobs. (I know, sorry, it's confusing, but basically if you were using SGE then --use_sge should always be on)

**Comment by ksahlin** [comment]
Thanks for you replies. I run ToFU. I think I first used the commands provided in the tutorial, i.e., with `--use_sge`. However, I convinced myself that since I'm running this in another cluster environment, I would not have to that parameter --- Our cluster environment would still be parallelize the work. I'm however unsure about the consequences with/without this parameter. Do you recommend this parameter to be used, even in another cluster environment?

I probably had unfinished jobs that were run with `--use_sge`, and resumed without that parameter. I will resume work around this soon and will rerun all jobs soon so maybe this issue will resolve itself --- by being consistent with the `--use_sge`.

Also, I noticed that the nfl.fa file output by classify is an (absolute) symlink, while the other output files are not. Is there a good reason for this? Some of the downstream unix steps (like moving this file with `mv` ) might fail because of this (my own experience). I got a request to bugreport this, using another developers words: "You also might want to log a bug report to the software using absolute symlinks, since it probably makes more sense to use relative symlinks." (from here https://bitbucket.org/snakemake/snakemake/issues/274/removing-nested-folders-when-shadow-full)

**Comment by Magdoll** [comment]
Hi,

(a) for post-processing, what matters is that you put --use_sge in if you did use it in running ToFU/ICE. 
for non-SGE systems, use --use_sge might break. This depends on whether your system also has the same signature for running qsub. In the past customers have altered ToFU to work with PBS and Condor (check the [homepage](https://github.com/PacificBiosciences/cDNA_primer/wiki) in the related tools section)

(b) @ylipacbio  can you explain the symbolic link reasoning for nFL reads?
