### ISSUE TITLE
collapse_isoforms_by_sam.py - ImportError: No module named modified_bx_intervals.intersection_unique

### ISSUE THREAD

**Issue by tzhughes** [PacificBiosciences/cDNA_primer#28]
Hi,

I am having trouble with getting collapse_isoforms_by_sam.py to run: I am getting **ImportError: No module named modified_bx_intervals.intersection_unique**

With your help back in November, I successfully installed the tofu version of pbtranscript.py (tofu_wrap.py also seems to have been successfully installed). But it does not seem like collapse_isoforms_by_sam.py has been successfully installed. I attach below the output I get when trying to run it. Not being a python programmer, it is rather difficult for me do to debug this, so I was hoping you would be able to help.

As you can see from the output below I have successfully followed the installation procedure and pbtranscript works fine.

```
(VENV_TOFU)(smrtshell-2.3.0) ubuntu@ip-10-169-66-19:~/home/bin/cDNA_primer$ which pbtranscript.py
/home/ubuntu/home/bin/VENV_TOFU/bin/pbtranscript.py

(VENV_TOFU)(smrtshell-2.3.0) ubuntu@ip-10-169-66-19:~/home/bin/cDNA_primer$ pbtranscript.py 
usage: pbtranscript.py [-h] [--verbose] [--version] [--profile] [--debug]
                       {classify,cluster,subset} ...


(VENV_TOFU)(smrtshell-2.3.0) ubuntu@ip-10-169-66-19:~/home/bin/cDNA_primer$ which collapse_isoforms_by_sam.py
/home/ubuntu/home/bin/VENV_TOFU/bin/collapse_isoforms_by_sam.py


(VENV_TOFU)(smrtshell-2.3.0) ubuntu@ip-10-169-66-19:~/home/bin/cDNA_primer$ collapse_isoforms_by_sam.py
Traceback (most recent call last):
  File "/home/ubuntu/home/bin/VENV_TOFU/bin/collapse_isoforms_by_sam.py", line 4, in <module>
    __import__('pkg_resources').run_script('pbtools.pbtranscript==2.2.3', 'collapse_isoforms_by_sam.py')
  File "/home/ubuntu/home/bin/VENV_TOFU/lib/python2.7/site-packages/pkg_resources/__init__.py", line 724, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/ubuntu/home/bin/VENV_TOFU/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1649, in run_script
    exec(code, namespace, namespace)
  File "/home/ubuntu/home/bin/VENV_TOFU/lib/python2.7/site-packages/pbtools.pbtranscript-2.2.3-py2.7-linux-x86_64.egg/EGG-INFO/scripts/collapse_isoforms_by_sam.py", line 42, in <module>
    from pbtools.pbtranscript.branch import branch_simple2
  File "/home/ubuntu/home/bin/VENV_TOFU/lib/python2.7/site-packages/pbtools.pbtranscript-2.2.3-py2.7-linux-x86_64.egg/pbtools/pbtranscript/branch/branch_simple2.py", line 4, in <module>
    import pbtools.pbtranscript.c_branch as c_branch
  File "c_branch.pyx", line 4, in init c_branch (pbtools/pbtranscript/branch/C/c_branch.c:5027)
ImportError: No module named modified_bx_intervals.intersection_unique

```

**Comment by Magdoll** [comment]
Hi,

As discussed in the [google group post](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/smrt_isoseq/dTRO50yX6Bg), this is probably due to a change in library import paths. Please give the fixes a try and see if it works! Thanks!

--Liz

**Comment by tzhughes** [comment]
See issue #3 for the solution to this bug.
File paths were not the issue in the latest version of master branch.
