### ISSUE TITLE
collapse_isoforms_by_sam.py IndexError: list index out of range error

### ISSUE THREAD

**Issue by peterdfields** [PacificBiosciences/cDNA_primer#31]
I observed the following in running the collapse_isoforms_by_sam.py:

Traceback (most recent call last):
  File "/home/peter/.pyenv/versions/2.7.9/bin/collapse_isoforms_by_sam.py", line 4, in <module>
    __import__('pkg_resources').run_script('pbtools.pbtranscript==2.2.3', 'collapse_isoforms_by_sam.py')
  File "/home/peter/.pyenv/versions/2.7.9/lib/python2.7/site-packages/pkg_resources/__init__.py", line 724, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/peter/.pyenv/versions/2.7.9/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1650, in run_script
    exec(code, namespace, namespace)
  File "/home/peter/.pyenv/versions/2.7.9/lib/python2.7/site-packages/pbtools.pbtranscript-2.2.3-py2.7-linux-x86_64.egg/EGG-INFO/scripts/collapse_isoforms_by_sam.py", line 261, in <module>
    main(args)
  File "/home/peter/.pyenv/versions/2.7.9/lib/python2.7/site-packages/pbtools.pbtranscript-2.2.3-py2.7-linux-x86_64.egg/EGG-INFO/scripts/collapse_isoforms_by_sam.py", line 222, in main
    collapse_fuzzy_junctions(f_good.name, f_txt.name, args.allow_extra_5exon, internal_fuzzy_max_dist=args.max_fuzzy_junction)
  File "/home/peter/.pyenv/versions/2.7.9/lib/python2.7/site-packages/pbtools.pbtranscript-2.2.3-py2.7-linux-x86_64.egg/EGG-INFO/scripts/collapse_isoforms_by_sam.py", line 170, in collapse_fuzzy_junctions
    _size = get_fl_from_id(group_info[pbid])
  File "/home/peter/.pyenv/versions/2.7.9/lib/python2.7/site-packages/pbtools.pbtranscript-2.2.3-py2.7-linux-x86_64.egg/EGG-INFO/scripts/collapse_isoforms_by_sam.py", line 113, in get_fl_from_id
    return sum(int(_id.split('/')[1].split('p')[0][1:]) for _id in members)
  File "/home/peter/.pyenv/versions/2.7.9/lib/python2.7/site-packages/pbtools.pbtranscript-2.2.3-py2.7-linux-x86_64.egg/EGG-INFO/scripts/collapse_isoforms_by_sam.py", line 113, in <genexpr>
    return sum(int(_id.split('/')[1].split('p')[0][1:]) for _id in members)
IndexError: list index out of range

This error seems quite different and I'd guess a different origin than described in the Troubleshooting ToFU page. The resulting gmap sam file was filtered for the problematic CIGAR entries. Also, given the recent changes described in Enhanced features for collapse script #9, I wondered if if this could be the possible basis of the error? The version of the script derives from the master branch downloaded on Feb. 6, 2015.

**Comment by Magdoll** [comment]
Hi,

What does your sequence ID look like?

collapse script expects a sequence ID format like:

c<unique_number>/f<number>p<number>/<sequence_length>

where the number after "f" says how many FL reads belong to this cluster. The number after "p" says how many nFL reads belong to this cluster.

ex:

c1/f3p99/1234
c2/f2p0/1000

If your sequence doesn't follow this format, you may have to hack your sequence to look so. I usually just fake with a FL count of 1 and a nFL count of 99.

**Comment by peterdfields** [comment]
That's probably the problem! Do you have a suggestion/script for hacking the names into the expected format?

**Comment by Magdoll** [comment]
You can do it via a Python script like the following. Modify as it suits to your ID format. Just make sure that each ID should be unique up to the first "/".

(this uses BioPython)

```
from Bio import SeqIO
f = open('output.fasta', 'w')
for r in SeqIO.parse(open(os.path.join(d, 'input.fasta')),'fasta'):
    raw = r.id.split('/')[0]
    newid = "{0}/f1p99/{1}".format(raw[0], len(r.seq))
    f.write(">{0}\n{1}\n".format(newid, r.seq))

f.close()

**Comment by peterdfields** [comment]
That's very useful! Thanks for the help, everything is running now!
