### ISSUE TITLE
IceCluster Error

### ISSUE THREAD

**Issue by wangxiv** [PacificBiosciences/cDNA_primer#56]
Hi,
I just run Ice cluster without Quiver.I get a final.consensus.fa successfuly when the input fasta sequence number is less than 20000,But failed when the number larger than 20000.I find the input file can be splitted into more files per 20000 when the number is larger than 20000 .My input file is 63779 fasta sequence which be splited into 4 files by the procedure.
the IceIterative log messege is :
……
[DEBUG] [IceIterative] 2016-11-01 12:53:41: [IceIterative] Picking up the very first sequence as reference.
[DEBUG] [IceIterative] 2016-11-01 12:53:41: [IceIterative] Choosing ref file for 32767 = clusterOutDir/tmp/3/c32767/in.fa.1stseq.fa
[INFO] [IceIterative] 2016-11-01 12:53:41: [IceIterative] Total time for choosing 18528 ref files is 0:01:46.754956.

# I think the IceIterative is not completed,but it exit with the error message below:
2016-11-01 12:53:45,491 [ERROR] Exiting pbtranscript with return code 1.
Traceback (most recent call last):
  File "smrt_analysis/p5/install/smrtanalysis_2.3.0.140936/analysis/bin/pbtranscript.py", line 146, in run
    obj.run()
  File "smrt_analysis/p5/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/pbtools/pbtranscript/Cluster.py", line 248, in run
    self.icec.run()
  File "smrt_analysis/p5/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/pbtools/pbtranscript/ice/IceIterative.py", line 1361, in run
    self.keep_adding_files(sizes=sizes)
  File "smrt_analysis/p5/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/pbtools/pbtranscript/ice/IceIterative.py", line 1226, in keep_adding_files
    self.add_new_batch(f)
  File "smrt_analysis/p5/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/pbtools/pbtranscript/ice/IceIterative.py", line 1144, in add_new_batch
    self.ensure_probQV_newid_consistency()
  File "smrt_analysis/p5/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/pbtools/pbtranscript/ice/IceIterative.py", line 1168, in ensure_probQV_newid_consistency
    self.probQV.get_smoothed(qID=rid, qvname='DeletionQV')
  File "ProbModel.pyx", line 237, in pbtools.pbtranscript.ice.ProbModel.ProbFromModel.get_smoothed (pbtools/pbtranscript/ice/C/ProbModel.cpp:5684)
TypeError: get_smoothed() takes at least 3 positional arguments (1 given)

The command is :
source smrt_analysis/p5/install/smrtanalysis_2.3.0.140936/etc/setup.sh
fofnToSmrtpipeInput.py input.fofn > input.xml 
pbtranscript.py  -v cluster --bas_fofn  input.fofn  -d cluster/clusterOutDir  --blasr_nproc 11  --unique_id 534404  --cDNA_size between1k2k  --report=cluster/isoseq_cluster_info.csv  --summary=cluster/cluster_summary.txt  primer.last.fasta  cluster/consensus_isoforms.fasta

I find the clusterOutDir/output/tmp.consensus.fa is 20000 input fasta cluster into 18035,that is  just 1 file run over in 4 files .There mybe something wrong bewteen the first file and the second file. 
I split the 63779 sequences into 2 files named A,B .Both respectively run Ice cluster with the same command as above.Both were splited into 2 files during runniing procedure and faild last.The IceIterative log message as below.
A:
[DEBUG] [IceIterative] 2016-11-01 13:45:24: [IceIterative] No more merges, break!
[INFO] [IceIterative] 2016-11-01 13:45:24: [IceIterative] Adding a new batch of fasta reads cluster/clusterOutDir/input.split_01.fa to clusters.
[ERROR] [IceIterative] 2016-11-01 13:45:24: [IceIterative] new batch file 
cluster/clusterOutDir/input.split_01.fa contains a read m160929_093844_42278_c101104082550000001823259904261730_s1_p0/54020/1827_23_CCS  of an existing cluster.

I find the first fie ,cluster/clusterOutDir/input.split_00.fa, had completed with 20000 sequences,and the second file, input.split_01.fa, had faile after reading 878 sequences with the error as above.

B:
……
[DEBUG] [IceIterative] 2016-11-01 13:43:37: [IceIterative] Picking up the very first sequence as reference.
[DEBUG] [IceIterative] 2016-11-01 13:43:37: [IceIterative] Choosing ref file for 29640 = cluster/clusterOutDir2/tmp/2/c29640/in.fa.1stseq.fa
[INFO] [IceIterative] 2016-11-01 13:43:37: [IceIterative] Total time for choosing 12992 ref files is 0:01:19.106673.

I think the IceIterative is not completed,but it exit with the same message  as 63779 fasta sequences run together.
Thanks for your help,
dong

**Comment by ylipacbio** [comment]
> new batch file cluster/clusterOutDir/input.split_01.fa contains a read m16…730_s1_p0/54020/1827_23_CCS of an existing cluster
This error message means that this CCS read already exists in the previous fasta. But we need to investigate why.
Would you please provide the isoseq_flnc.fasta file for trouble shooting? Thanks!
