### ISSUE TITLE
MatchAnnot-master/clusterView.py  Error

### ISSUE THREAD

**Issue by Dongxn** [PacificBiosciences/cDNA_primer#60]
Hi, I am running MatchAnnot and came to an error message below:
[DEBUG] 2016-11-28 16:33:28,562 [Annotations 13] version 20150611.01 loaded
[DEBUG] 2016-11-28 16:33:28,601 [Cluster 13] version 20150814.01 loaded
[DEBUG] 2016-11-28 16:33:28,618 [CigarString 15] version 20150707.01 loaded
[DEBUG] 2016-11-28 16:33:28,620 [clusterView 46] version 20150529.01 starting
[DEBUG] 2016-11-28 16:33:28,621 [Annotations 134] reading annotations in standard format from /Genome/Oryza_sativa_Japonica.IRGSP-1.0.gtf
[DEBUG] 2016-11-28 16:33:48,258 [Annotations 213] read 35679 genes, 42346 transcripts, 190117 exons
[DEBUG] 2016-11-28 16:33:48,258 [Annotations 367] creating gene name lookup table
[WARNING] 2016-11-28 16:33:48,281 [clusterView 129] gene 1 appears 35679 times in annotations, first occurrence plotted
[DEBUG] 2016-11-28 16:33:58,375 [Cluster 88] read 26310 clusters in pickle format from /Analysis/MatchAnno/MatchAnno.pickle
[DEBUG] 2016-11-28 16:34:01,772 [clusterView 254] kept 25426 of 25426 clusters for gene 1
[DEBUG] 2016-11-28 16:34:01,773 [clusterView 255] kept clusters include 48263 full + 74055 partial reads
[DEBUG] 2016-11-28 16:34:04,457 [clusterView 366] found 119224 regions
[DEBUG] 2016-11-28 16:54:10,556 [clusterView 77] nTrans: 25427  vertSize: 5086.40  margin:  0.00
Traceback (most recent call last):
  File "/software/SMRT/MatchAnnot-master/clusterView.py", line 805, in <module>
    main()
  File "/software/SMRT/MatchAnnot-master/clusterView.py", line 98, in main
    plt.savefig (opt.output)
  File "/Python/2.7.8/lib/python2.7/site-packages/matplotlib-1.4.3-py2.7-linux-x86_64.egg/matplotlib/pyplot.py", line 577, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/Python/2.7.8/lib/python2.7/site-packages/matplotlib-1.4.3-py2.7-linux-x86_64.egg/matplotlib/figure.py", line 1476, in savefig
    self.canvas.print_figure(*args, **kwargs)
  File "/Python/2.7.8/lib/python2.7/site-packages/matplotlib-1.4.3-py2.7-linux-x86_64.egg/matplotlib/backend_bases.py", line 2211, in print_figure
    **kwargs)
  File "/Python/2.7.8/lib/python2.7/site-packages/matplotlib-1.4.3-py2.7-linux-x86_64.egg/matplotlib/backends/backend_agg.py", line 521, in print_png
    FigureCanvasAgg.draw(self)
  File "/Python/2.7.8/lib/python2.7/site-packages/matplotlib-1.4.3-py2.7-linux-x86_64.egg/matplotlib/backends/backend_agg.py", line 464, in draw
    self.renderer = self.get_renderer(cleared=True)
  File "/Python/2.7.8/lib/python2.7/site-packages/matplotlib-1.4.3-py2.7-linux-x86_64.egg/matplotlib/backends/backend_agg.py", line 481, in get_renderer
    self.renderer = RendererAgg(w, h, self.figure.dpi)
  File "/Python/2.7.8/lib/python2.7/site-packages/matplotlib-1.4.3-py2.7-linux-x86_64.egg/matplotlib/backends/backend_agg.py", line 94, in __init__
    self._renderer = _RendererAgg(int(width), int(height), dpi, debug=False)
ValueError: width and height must each be below 32768

**Comment by Magdoll** [comment]
Hi @Dongxn I know this is an old issue, but I'm going to redirect your attention to a newer software that is more up to date and does the same things. Check out Iso-Seq Browser https://github.com/goeckslab/isoseq-browser and hopefully it will address your needs.
