### ISSUE TITLE
ICEQUIVER AssertionError

### ISSUE THREAD

**Issue by henryxushi** [PacificBiosciences/cDNA_primer#61]
Hi,

I tried to run ICEQUIVER with pbtranscript-tofu, but got an AssertionError. Here is the command I use
`pbtranscript.py cluster ccs.isoseq_flnc.fasta final.consensus.fa --nfl_fa ccs.isoseq_nfl.fasta -d cluster --ccs_fofn reads_of_insert.fofn --bas_fofn input.fofn --quiver --blasr_nproc 15 --quiver_nproc 8`

Here is the traceback
```
2016-12-06 18:09:23,757 [ERROR] Exiting pbtranscript with return code 1.
Traceback (most recent call last):
  File "/home/cbil/Henry/RNA-seq/PacBio/pbtranscript-tofu/VENV_TOFU/lib/python2.7/site-packages/pbtools.pbtranscript-2.2.3-py2.7-linux-x86_64.egg/EGG-INFO/scripts/pbtranscript.py", line 154, in run
    obj.run()
  File "/home/cbil/Henry/RNA-seq/PacBio/pbtranscript-tofu/VENV_TOFU/local/lib/python2.7/site-packages/pbtools.pbtranscript-2.2.3-py2.7-linux-x86_64.egg/pbtools/pbtranscript/Cluster.py", line 271, in run
    use_ccs_qv=self.ice_opts.use_finer_qv)
  File "/home/cbil/Henry/RNA-seq/PacBio/pbtranscript-tofu/VENV_TOFU/local/lib/python2.7/site-packages/pbtools.pbtranscript-2.2.3-py2.7-linux-x86_64.egg/pbtools/pbtranscript/ice/IceIterative.py", line 214, in __init__
    self.calc_cluster_prob(force_calc=True)
  File "/home/cbil/Henry/RNA-seq/PacBio/pbtranscript-tofu/VENV_TOFU/local/lib/python2.7/site-packages/pbtools.pbtranscript-2.2.3-py2.7-linux-x86_64.egg/pbtools/pbtranscript/ice/IceIterative.py", line 935, in calc_cluster_prob
    self.g2(query_obj, ref_obj, las_out_filenames)
  File "/home/cbil/Henry/RNA-seq/PacBio/pbtranscript-tofu/VENV_TOFU/local/lib/python2.7/site-packages/pbtools.pbtranscript-2.2.3-py2.7-linux-x86_64.egg/pbtools/pbtranscript/ice/IceIterative.py", line 959, in g2
    same_strand_only=True, no_qv_or_aln_checking=False):
  File "/home/cbil/Henry/RNA-seq/PacBio/pbtranscript-tofu/VENV_TOFU/local/lib/python2.7/site-packages/pbtools.pbtranscript-2.2.3-py2.7-linux-x86_64.egg/pbtools/pbtranscript/icedalign/IceDalignReader.py", line 71, in dalign_against_ref
    for r in LAshowAlignReader(las_out_filename):
  File "/home/cbil/Henry/RNA-seq/PacBio/pbtranscript-tofu/VENV_TOFU/local/lib/python2.7/site-packages/pbtools.pbtranscript-2.2.3-py2.7-linux-x86_64.egg/pbtools/pbtranscript/icedalign/IceDalignReader.py", line 48, in next
    assert (qStrand == 0 and int(_qStart)-1 == qStart) or (qStrand == 1 and int(_qStart)-1 == qLen-qEnd)
AssertionError

```
I have checked the file input.split_000.dazz.fasta.1.ref_consensus.dazz.fasta.1.N0.las.out to understand the assertion at line 48 of IceDalignReader.py. It seems that `qStrand == 0 and int(_qStart) == qStart` is my case. Could you please help me solve this problem? Another quick question: why int(_qStart)-1 has to be equal to qStart? I am using blasr 5.1, is there any incompatibility?

Thanks,
Henry

**Comment by henryxushi** [comment]
I have figured it out. It is actually a version incompatibility issue. When I use blasr 1.3.1, it works without errors.
