### ISSUE TITLE
Running tofu_wrap.py would raise "Error loading chemistry mapping xml"

### ISSUE THREAD

**Issue by yang91** [PacificBiosciences/cDNA_primer#62]
Hi,

    I installed the tofu-prebam version in Ubuntu 16.04.01 enviroment, while the installation successed, it would raise error when running tofu_wrap.py:

```
Traceback (most recent call last):
  File "/home2/smrtanalysis/tofu/bin/tofu_wrap.py", line 5, in <module>
    pkg_resources.run_script('pbtools.pbtranscript==2.2.3', 'tofu_wrap.py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/home2/smrtanalysis/tofu/lib/python2.7/site-packages/pbtools.pbtranscript-2.2.3-py2.7-linux-x86_64.egg/EGG-INFO/scripts/tofu_wrap.py", line 4, in <module>
    from pbcore.io.FastaIO import FastaReader
  File "/home2/smrtanalysis/tofu/local/lib/python2.7/site-packages/pbcore/io/__init__.py", line 31, in <module>
    from .BasH5IO import *
  File "/home2/smrtanalysis/tofu/local/lib/python2.7/site-packages/pbcore/io/BasH5IO.py", line 44, in <module>
    from pbcore.chemistry import (decodeTriple,
  File "/home2/smrtanalysis/tofu/local/lib/python2.7/site-packages/pbcore/chemistry/__init__.py", line 31, in <module>
    from .chemistry import *
  File "/home2/smrtanalysis/tofu/local/lib/python2.7/site-packages/pbcore/chemistry/chemistry.py", line 63, in <module>
    _BARCODE_MAPPINGS = _loadBarcodeMappings()
  File "/home2/smrtanalysis/tofu/local/lib/python2.7/site-packages/pbcore/chemistry/chemistry.py", line 61, in _loadBarcodeMappings
    return _loadBarcodeMappingsFromFile(mappingFname)
  File "/home2/smrtanalysis/tofu/local/lib/python2.7/site-packages/pbcore/chemistry/chemistry.py", line 57, in _loadBarcodeMappingsFromFile
    raise ChemistryLookupError, "Error loading chemistry mapping xml"
pbcore.chemistry.chemistry.ChemistryLookupError: Error loading chemistry mapping xml

```

   I couldn't found any solution to it, did anyone know how to fix it? 

PS：
the SMRT Analysis Softwared was already installed (version 2.3) and all the installaions were under the smrtshell and virtual environment. Python version on the server is 2.7.11, and all installed python packages are showed as bleow:

bx-python (0.7.3)
cycler (0.10.0)
Cython (0.20.1)
decorator (4.0.10)
h5py (2.6.0)
hashlib (20081119)
hmac (20101005)
matplotlib (1.5.3)
networkx (1.11)
numpy (1.7.1)
pbcore (1.2.1)
pbtools.pbtranscript (2.2.3)
pip (9.0.1)
pygobject (3.20.0)
pyparsing (2.1.10)
pysam (0.8.1)
python-dateutil (2.6.0)
pytz (2016.10)
scour (0.32)
setuptools (3.6)
six (1.10.0)
urllib3 (1.19.1)
wheel (0.29.0)

**Comment by ylipacbio** [comment]
It failed to read chemistry xml file at `/home2/smrtanalysis/tofu/local/lib/python2.7/site-packages/pbcore/chemistry/resources/mapping.xml`

Can you find this mapping.xml file?

**Comment by yang91** [comment]
Hi @ylipacbio ,
    Yes, here is a mapping.xml file under /home2/smrtanalysis/tofu/local/lib/python2.7/site-packages/pbcore/chemistry/resources/ dir.
