### ISSUE TITLE
error about pbtranscript-tofu

### ISSUE THREAD

**Issue by jjian4827** [PacificBiosciences/cDNA_primer#63]
After I successfully install pbtranscript-tofu step by step following  https://github.com/PacificBiosciences/cDNA_primer/wiki/Setting-up-virtualenv-and-installing-pbtranscript-tofu , I try to type fusion_funder.py. It return me : 
(VENV_TOFU)(smrtshell-2.3.0) [R03@mgmt C]$ fusion_finder.py 
Traceback (most recent call last):
  File "/home/transcriptome/software/pbtranscript_tofu/VENV_TOFU/bin/fusion_finder.py", line 4, in <module>
    __import__('pkg_resources').run_script('pbtools.pbtranscript==2.2.3', 'fusion_finder.py')
  File "/home/transcriptome/software/pbtranscript_tofu/VENV_TOFU/lib/python2.7/site-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/transcriptome/software/pbtranscript_tofu/VENV_TOFU/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1494, in run_script
    exec(code, namespace, namespace)
  File "/home/transcriptome/software/pbtranscript_tofu/VENV_TOFU/lib/python2.7/site-packages/pbtools.pbtranscript-2.2.3-py2.7-linux-x86_64.egg/EGG-INFO/scripts/fusion_finder.py", line 10, in <module>
    import pbtools.pbtranscript.branch.branch_simple2 as branch_simple2
  File "/home/transcriptome/software/pbtranscript_tofu/VENV_TOFU/lib/python2.7/site-packages/pbtools.pbtranscript-2.2.3-py2.7-linux-x86_64.egg/pbtools/pbtranscript/branch/branch_simple2.py", line 4, in <module>
    import pbtools.pbtranscript.c_branch as c_branch
  File "c_branch.pyx", line 4, in init c_branch (pbtools/pbtranscript/branch/C/c_branch.c:5027)
    from pbtools.pbtranscript.modified_bx_intervals.intersection_unique import IntervalTreeUnique, Interval
ImportError: No module named modified_bx_intervals.intersection_unique

The same problem occurred when I try to use collapse_isoforms_by_sam.py. Is there any thing wrong with my pbtranscript-tofu?

**Comment by ylipacbio** [comment]
Seems like cython code `pbtools/pbtranscript/branch/C/modified_bx_intervals/intersection_unique.pyx` is not installed correctly.

One way to check is to run the command below:
`find  /home/transcriptome/software/pbtranscript_tofu/VENV_TOFU/lib/python2.7/site-packages/pbtools.pbtranscript-2.2.3-py2.7-linux-x86_64.egg/pbtools/pbtranscript -type f -name intersection_unique.so`

**Comment by jjian4827** [comment]
@ylipacbio 
        Thank you very much for reply.
        I typed the command  "find /home/transcriptome/software/pbtranscript_tofu/VENV_TOFU/lib/python2.7/site-packages/pbtools.pbtranscript-2.2.3-py2.7-linux-x86_64.egg/pbtools/pbtranscript -type f -name intersection_unique.so" as you suggested. And the result is :
        /home/transcriptome/software/pbtranscript_tofu/VENV_TOFU/lib/python2.7/site-packages/pbtools.pbtranscript-2.2.3-py2.7-linux-x86_64.egg/pbtools/pbtranscript/modified_bx_intervals/intersection_unique.so
        Is there any wrong about the path of  modified_bx_intervals/intersection_unique.so?

**Comment by Magdoll** [comment]
This is a known issue. 
Please follow this hack fix here:
https://github.com/PacificBiosciences/cDNA_primer/issues/3

**Comment by jjian4827** [comment]
@Magdoll ,
        Thank you very much! My pbtranscript-tofu can be used now.
