### ISSUE TITLE
ImportError when running tofu

### ISSUE THREAD

**Issue by yang91** [PacificBiosciences/cDNA_primer#65]
Hi,

     For some reason, I re-installed Ubuntu system with version 16.04. Then I reinstalled SMRT Analysis Software and pbtranscript-tofu, but it would reported below error when running pbtranscript-tofu:
`python tofu/bin/pbtranscript.py
Traceback (most recent call last):
  File "tofu/bin/pbtranscript.py", line 4, in <module>
    __import__('pkg_resources').run_script('pbtools.pbtranscript==2.2.3', 'pbtranscript.py')
  File "/home2/smrtanalysis/tofu/lib/python2.7/site-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home2/smrtanalysis/tofu/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1494, in run_script
    exec(code, namespace, namespace)
  File "/home2/smrtanalysis/tofu/lib/python2.7/site-packages/pbtools.pbtranscript-2.2.3-py2.7-linux-x86_64.egg/EGG-INFO/scripts/pbtranscript.py", line 37, in <module>
    from pbtools.pbtranscript.Classifier import Classifier, ChimeraDetectionOptions
  File "/home2/smrtanalysis/tofu/lib/python2.7/site-packages/pbtools.pbtranscript-2.2.3-py2.7-linux-x86_64.egg/pbtools/pbtranscript/Classifier.py", line 10, in <module>
    from pbcore.io.FastaIO import FastaReader, FastaWriter
  File "/home2/smrtanalysis/tofu/lib/python2.7/site-packages/pbcore/io/__init__.py", line 38, in <module>
    from .align   import *
  File "/home2/smrtanalysis/tofu/lib/python2.7/site-packages/pbcore/io/align/__init__.py", line 32, in <module>
    from BamIO          import *
  File "/home2/smrtanalysis/tofu/lib/python2.7/site-packages/pbcore/io/align/BamIO.py", line 35, in <module>
    from pysam import AlignmentFile
  File "/home2/smrtanalysis/tofu/lib/python2.7/site-packages/pysam/__init__.py", line 5, in <module>
    from pysam.libchtslib import *
ImportError: /usr/lib/x86_64-linux-gnu/libkrb5.so.26: undefined symbol: com_right_r
` 
 There seems like nobody have met this issue and searching in google didn't give me much help too. Could anyone help for me to solve this? 

Detailed settings:
```
python version: 2.7.3

bx-python (0.7.3)
Cython (0.25.2)
h5py (2.6.0)
hashlib (20081119)
hmac (20101005)
numpy (1.12.0)
pbcore (1.2.10)
pbtools.pbtranscript (2.2.3)
pip (9.0.1)
pysam (0.9.1.4)
setuptools (33.1.1)
six (1.10.0)
urllib3 (1.19.1)
wheel (0.29.0)
```

**Comment by mhsieh** [comment]
Hi, please check your local home directory and see if you have pip cache in your system, e.g. ~/.cache/pip/wheels/*/*/*/*/*-linux_x86_64.whl and you should remove all *-linux_x86_64.whl file before you rebuilt the pbtranscript-tofu environment.

**Comment by uqvirg** [comment]
Hi,
I have the same issue. The different PATH don't seem to be initialized or configured.
If somebody has a solution, it will be great ! It's a python configuration pbs but how to fix it ?
Thanks,
Virginie

**Comment by mhsieh** [comment]
The more I see this, this looks more like a problem of compatibility issue of old smrtanalysis 2.x release with ubuntu 16. Here are some possible solution:
1. Using an older operating system (could be on a new host or a new VM) that smrtanalysis 2.x supports.
2. follow the pbtranscript-tofu document and take the pitchfork route, it might be harder this way, but I probably should help.
