### ISSUE TITLE
ICE_Quiver Error

### ISSUE THREAD

**Issue by nikou123456** [PacificBiosciences/cDNA_primer#76]
Hello! 
  The analysis crashes during clustering step（ICE_Quiver） on SMRTanalysis_2.3.0., I don't know why cause the following problem :
   **1. First**,I pool same size sample to a single one, such I have 2 cell on size fraction 1-2KB
      cat leaf_lsf_ccs_1k2k_1.input.fofn leaf_lsf_ccs_1k2k_2.input.fofn  > leaf_lsf_ccs.input.fofn
      cat leaf_reads_of_insert_1k2k_1.fofn  leaf_reads_of_insert_1k2k_2.fofn > leaf_reads_of_insert.fofn
      cat isoseq_nfl_1k2k_1.fasta   isoseq_nfl_1k2k_2.fasta  > isoseq_nfl.fasta
      cat leaf_isoseq_nfl_1k2k_1.fasta leaf_isoseq_nfl_1k2k_2.fasta  >   leaf_isoseq_nfl.fasta
   **2. second** , ICE_Quiver
      pbtranscript.py cluster 
                         "/data/gpfs01/gjli/seven/Amborella/Isoseq/pool2/leaf/leaf1k2k/leaf_isoseq_flnc.fasta" \
                         "/data/gpfs01/gjli/seven/Amborella/Isoseq/pool2/leaf/leaf1k2k/leaf_final.consensus.fa" \
                 --nfl_fa "/data/gpfs01/gjli/seven/Amborella/Isoseq/pool2/leaf/leaf1k2k/leaf_isoseq_nfl.fasta" \
                 -d cluster \
                 --ccs_fofn 
                "/data/gpfs01/gjli/seven/Amborella/Isoseq/pool2/leaf/leaf1k2k/leaf_reads_of_insert.fofn" \
                 --bas_fofn "/data/gpfs01/gjli/seven/Amborella/Isoseq/pool2/leaf/leaf1k2k/leaf_lsf_ccs.input.fofn" \
                 --cDNA_size under1k --quiver \
                 --blasr_nproc 24 --quiver_nproc 8 \
                 --report  "/data/gpfs01/gjli/seven/Amborella/Isoseq/pool2/leaf/leaf1k2k/cluster_report.txt" \
                 --summary "/data/gpfs01/gjli/seven/Amborella/Isoseq/pool2/leaf/leaf1k2k/cluster_summary.txt" 

Then,I get following error information:
2017-11-03 13:12:31,682 INFO [main] Multi-threaded. Input: /data/gpfs01/gjli/seven/Amborella/Isoseq/pool2/leaf/leaf1k2k/cluster/tmp/0/c900/g_consensus.saln, Threads: 8
[INFO] 2017-11-03T13:12:31 [blasr] started.
[INFO] 2017-11-03T13:12:31 [blasr] ended.
[INFO] 2017-11-03T13:12:31 [blasr] started.
[INFO] 2017-11-03T13:12:31 [blasr] ended.
2017-11-03 13:12:31,943 INFO [main] Multi-threaded. Input: /data/gpfs01/gjli/seven/Amborella/Isoseq/pool2/leaf/leaf1k2k/cluster/tmp/1/c14219/g_consensus.saln, Threads: 8
2017-11-03 13:12:46,976 INFO [main] Multi-threaded. Input: /data/gpfs01/gjli/seven/Amborella/Isoseq/pool2/leaf/leaf1k2k/cluster/tmp/1/c14249/g_consensus.saln, Threads: 8
**2017-11-05 00:31:20,105 [ERROR] Exiting pbtranscript with return code 1.**
Traceback (most recent call last):
  File "/data/gpfs01/gjli/smrt/install/smrtanalysis_2.3.0.140936/analysis/bin/pbtranscript.py", line 145, in run
    summary_fn=self.args.summary_fn)
  File "/data/gpfs01/gjli/smrt/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/pbtools/pbtranscript/Cluster.py", line 58, in __init__
    root_dir, out_fa)
  File "/data/gpfs01/gjli/smrt/install/smrtanalysis_2.3.0.140936/redist/python2.7/lib/python2.7/site-packages/pbtools/pbtranscript/Cluster.py", line 141, in _validate_outputs
    format(f=out_fa))
**ClusterException: command: cluster raised the following error: Consensus FASTA file /data/gpfs01/gjli/seven/Amborella/Isoseq/pool2/leaf/leaf1k2k/leaf_final.consensus.fa already exists.**

I really hope to get your help!

**Comment by Magdoll** [comment]
Hi,
In which directory are you running the `pbtranscript cluster ...` command?
I assume it's `/data/gpfs01/gjli/seven/Amborella/Isoseq/pool2/leaf/leaf1k2k/`. So that means the cluster results will be written in `/data/gpfs01/gjli/seven/Amborella/Isoseq/pool2/leaf/leaf1k2k/cluster/` and the final consensus file will be symbolically linked to `/data/gpfs01/gjli/seven/Amborella/Isoseq/pool2/leaf/leaf1k2k/leaf_final.consensus.fa`.

Can you check that `/data/gpfs01/gjli/seven/Amborella/Isoseq/pool2/leaf/leaf1k2k/leaf_final.consensus.fa` does not already exist?

That's what the error message is complaining about. You may be running the job in a directory with previously existing results and it does not want to override them.
--Liz

**Comment by nikou123456** [comment]
Hi, I'am sure` /data/gpfs01/gjli/seven/Amborella/Isoseq/pool2/leaf/leaf1k2k/leaf_final.consensus.fa` does not already exist. I will create a new directury before opration, such as 
```
#!/bin/bash
[ -e /data/gpfs01/gjli/seven/Amborella/Isoseq/pool2/leaf/leaf1k2k ]
if [ $? -eq 0 ] ;then
rm -f /data/gpfs01/gjli/seven/Amborella/Isoseq/pool2/leaf/leaf1k2k
mkdir /data/gpfs01/gjli/seven/Amborella/Isoseq/pool2/leaf/leaf1k2k
fi
```
However, it's very strange, yesterday I used same command operation based on the same data, result no error only some warning
```
[INFO] 2017-11-07T07:50:12 [blasr] started.
[INFO] 2017-11-07T07:50:12 [blasr] ended.
[INFO] 2017-11-07T07:50:12 [blasr] started.
[INFO] 2017-11-07T07:50:12 [blasr] ended.
2017-11-07 07:50:12,692 INFO [main] Multi-threaded. Input: /data/gpfs01/gjli/seven/Amborella/Isoseq/pool2/leaf/leaf1k2k/try/cluster/tmp/2/c28671/g_consensus.saln, Threads: 8
2017-11-07 08:12:42,152 [WARNING] Ignoring m140929_201346_42154_c100686982550000001823134802221512_s1_p0/106856 because the input fasta_fofn does not contain its sequence.
2017-11-07 09:19:15,501 [WARNING] Ignoring m140929_201346_42154_c100686982550000001823134802221512_s1_p0/106856 because the input fasta_fofn does not contain its sequence.
2017-11-07 09:56:42,966 [WARNING] Ignoring m140929_201346_42154_c100686982550000001823134802221512_s1_p0/106856 because the input fasta_fofn does not contain its sequence.
2017-11-07 10:14:37,414 [WARNING] Ignoring m140929_201346_42154_c100686982550000001823134802221512_s1_p0/106856 because the input fasta_fofn does not contain its sequence.
2017-11-07 10:19:34,980 [WARNING] Ignoring m140929_201346_42154_c100686982550000001823134802221512_s1_p0/106856 because the input fasta_fofn does not contain its sequence.
```
Thank you very much for your advice, 
Best regards !

**Comment by Magdoll** [comment]
Hi @nikou123456 ,

The warning messages 

```
Ignoring m140929_201346_42154_c100686982550000001823134802221512_s1_p0/106856 because the input fasta_fofn does not contain its sequence
```

suggests that the input FLNC sequences are not necessarily in the correct format.

An expected FLNC (CCS) format is: `<movie>/<zmw>/<start>_<end>_CCS`

For example:

```
m140929_201346_42154_c100686982550000001823134802221512_s1_p0/30/1_100_CCS
m140929_201346_42154_c100686982550000001823134802221512_s1_p0/40/700_12_CCS
```

Also, I hate to point this out, but you are using a very old version of SMRTAnalysis (2.3) which would contain bugs/issues we would have fixed in later versions. Do you have access to a newer version of SMRTAnalysis (the latest is 5.x)? 


--Liz

**Comment by nikou123456** [comment]
Hi Liz:，
  I appreciate your help and your patience, I still use SMRTAnalysis(2.3) for data analysis and so far,so good.  I will follow your advice for remaining data if necessary.
Thank you very much for,
Best regards !

**Comment by Magdoll** [comment]
Hi @nikou123456 ,

As I wrote earlier, the warning messages from your run suggest something is off in the input data, possibly meaning you have provided data formats that were inconsistent with expectations or that you are using the wrong data. Please make sure to verify them and if you see strange results, post them here so we can troubleshoot further.

--Liz
